data_directory = '/var/lib/yince-db/data'
hba_file = '/etc/yince-db/pg_hba.conf'
ident_file = '/var/lib/yince-db/data/pg_ident.conf'
listen_addresses = ''
port = 55433
unix_socket_directories = '/run/yince-db'
unix_socket_permissions = 0770
max_connections = 20
superuser_reserved_connections = 3
shared_buffers = '32MB'
work_mem = '2MB'
maintenance_work_mem = '16MB'
autovacuum_work_mem = '16MB'
autovacuum_max_workers = 1
max_worker_processes = 2
max_parallel_workers = 0
max_parallel_workers_per_gather = 0
jit = off
password_encryption = 'scram-sha-256'
statement_timeout = '10s'
idle_in_transaction_session_timeout = '15s'
log_destination = 'stderr'
logging_collector = off
log_statement = 'none'
log_min_error_statement = 'panic'
log_line_prefix = '%m [yince-db:%p] '
timezone = 'Asia/Shanghai'
log_timezone = 'Asia/Shanghai'
dynamic_library_path = '/srv/yince-db/runtime/usr/lib/postgresql/14/lib'
